### ISSUE TITLE
BPMs are parsed incorrectly on other locales

### ISSUE THREAD

**Issue by zkldi** [PerryAsleep/StepManiaLibrary#1]
Standard C#/locale footgun.

On locales where `,` is the decimal separator `#BPMS:0.000=125.000;` parses not as a bpm of `125.000` but as a bpm of `125000`.

**Comment by PerryAsleep** [comment]
Thanks for catching this!

Should be fixed in 3dd1a1979dad05e6d9d7d3c8a626129cf14d1ee3.
